version: '3.9'

services:

  postgres_tasks_db:
    container_name: postgres_tasks_db
    image: postgres:15-alpine
    volumes:
      - pg-tasks-data:/var/lib/postgresql/data
    networks:
      - dev-network
    env_file:
      - .env
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 30s
      interval: 30s
      timeout: 30s
      retries: 3


  tasks:
    container_name: tasks
    build: ./
    networks:
      - dev-network
    ports:
      - ${TASKS_PORT}:${TASKS_PORT}
      - "13714:13714"
    depends_on:
      postgres_tasks_db:
        condition: service_healthy
        restart: true
    env_file: 
      - .env

volumes:
  pg-tasks-data:

networks:
  dev-network:
    driver: bridge